<a href="https://colab.research.google.com/github/graceknav/Linear_Algebra_Coding_projects/blob/main/PracticeExam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import c_

ll = "loaded"

In [9]:
M = np.matrix([[40/100, 50/100, 20/100, 0],
               [30/100, 0, 40/100, 0],
               [30/100, 0, 40/100, 0],
               [0, 50/100, 0, 1]])

In [10]:
x0 = np.matrix([[100], [200], [0], [0]])

In [11]:
(M**10)*x0

matrix([[ 23.47657277],
        [ 15.36902454],
        [ 15.36902454],
        [245.78537815]])

In [12]:
(M**20)*x0

matrix([[  5.09109406],
        [  3.33290341],
        [  3.33290341],
        [288.24309911]])

In [13]:
(M**240)*x0

matrix([[1.26675449e-14],
        [8.29285479e-15],
        [8.29285479e-15],
        [3.00000000e+02]])

In [14]:
(M**5)*x0

matrix([[ 50.414],
        [ 33.003],
        [ 33.003],
        [183.58 ]])

In [19]:
(M**1)*x0

matrix([[140.],
        [ 30.],
        [ 30.],
        [100.]])